### ISSUE TITLE
Minimum nema required (totally noob question)

### ISSUE THREAD

**Issue by biaggi** [tjfenwick/DIY-Sim-Racing-Active-Pedal#3]
Hi I was wondering If I could try to build one with a 3d printer nema 11 or so or it just makes no sense

What do u think?

**Comment by tjfenwick** [comment]
Hi, a nema 11 or even 17 stepper motor won't have enough torque or spin
fast enough to give you a realistic pedal feel.

Thanks,
Tristian

**Comment by biaggi** [comment]
Thank u for your response, I'll check the specifications of the one you are using
